# https://www.yamllint.com/ - YAML Validator
# https://docs.docker.com/compose/ - Docker Compose

name: discord-bot
services:
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    environment:
      - 'DISCORD_TOKEN=${DISCORD_TOKEN}'
    restart: unless-stopped